### ISSUE TITLE
support MMU  ?

### ISSUE THREAD

**Issue by hongshui3000** [pulp-platform/pulp#1]
![image](https://user-images.githubusercontent.com/25566498/36775021-3be9bd26-1c9b-11e8-9c70-92f6283abdea.png)

**Comment by daviderossi1982** [comment]
It's not a "traditional" mmu, it was meant to change the interleaving address scheme of the TCDM when some of the banks are off. you can find more info here: https://ieeexplore.ieee.org/abstract/document/8065010/. This feature is not supported in the current open-source version.
