### ISSUE TITLE
flatpak functionality update?

### ISSUE THREAD

**Issue by jonasbartho** [pulp-platform/pulp#14]
Hi,

Ref. https://pulp.plan.io/projects/pulp/wiki/Flatpak

Is there any progress/update on this? This would be a great asset if you guys were able to implement flatpak functionality into pulp.. :)

Kinds regards,
Jonas

**Comment by FrancescoConti** [comment]
I think you went to the wrong repository. This PULP is a open hardware platform you are probably looking for something different....
