### ISSUE TITLE
build pulp sdk failed

### ISSUE THREAD

**Issue by 869523031** [pulp-platform/pulp#21]
I'm following the tutorial on PULP SDK build process ,I'm blocked at the stage of SDK build when I tape the command "$ make all" and I can't understand what's mean these errors.

git submodule update --init
source init.sh && ./pulp-tools/bin/plpbuild --p sdk checkout build env --stdout
Configuring Pulp project at /root/pulpshp/pulp-sdk
FATAL ERROR: Configurations must e given either through PULP_CURRENT_CONFIG or PULP_CONFIGS
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 255

Waitting for your help

**Comment by milos-tomic** [comment]
I'm facing the same issue. It looks for the environmental variables and fails if they are not defined:

What is strange is that I checked PULP_CURRENT_CONFIG and it is set:
```
echo $PULP_CURRENT_CONFIG
pulpissimo@config_file=chips/pulpissimo/pulpissimo_ibex.json
```
I'm not sure if this is good though... It is a value from the config file I sourced. I tried different configs, but always the same error.

**Comment by milos-tomic** [comment]
@869523031 Did you try `echo` command on environmental variable? They should be set with "source configs/<config_file>"
I just found the answer to my question in this thread: https://pulp-platform.org/community/printthread.php?tid=132
I was executing the command using with `sudo` prefix and that caused the issue.

**Comment by FrancescoConti** [comment]
Running anything related to PULP as root (i.e. prepended with `sudo`) is **definitely** not recommended -- the only exception is installing packages with APT or similar.
