### ISSUE TITLE
can pulp support vcs simulation?

### ISSUE THREAD

**Issue by weiqi7777** [pulp-platform/pulp#28]
hi:
 from the Makefile, I find the pulp can compile with vsim and xrun. but pulp can't compile with vcs. 
can pul support vcs simulation?

thanks
lujun

**Comment by FrancescoConti** [comment]
It can, in the sense that the code is synthesizable and well-supported, we expect no problem running it with VCS. But we do not use VCS internally, so the compilation script generation etc. do not target it at the moment.
