### ISSUE TITLE
prerequisite for pulp-sdk failed 

### ISSUE THREAD

**Issue by amitgargmentor** [pulp-platform/pulp#31]
Hi,

As pre-requisite of pulp-sdk, we need to install below package:

**sudo yum install git python36-pip python36-devel gawk texinfo gmp-devel mpfr-devel libmpc-devel swig libjpeg-turbo-devel redhat-lsb-core doxygen python-sphinx sox GraphicsMagick-devel ImageMagick-devel SDL2-devel perl-Switch libftdi-devel cmake cmake3 scons**

But i see the Below error while installing SDL2-dlevel : 

**Resolving Dependencies
--> Running transaction check
---> Package SDL2-devel.x86_64 0:2.0.10-1.el7 will be installed
--> Processing Dependency: SDL2(x86-64) = 2.0.10-1.el7 for package: SDL2-devel-2.0.10-1.el7.x86_64
--> Processing Dependency: mesa-libGLES-devel(x86-64) for package: SDL2-devel-2.0.10-1.el7.x86_64
--> Processing Dependency: libSDL2-2.0.so.0()(64bit) for package: SDL2-devel-2.0.10-1.el7.x86_64
--> Running transaction check
---> Package SDL2.x86_64 0:2.0.10-1.el7 will be installed
---> Package SDL2-devel.x86_64 0:2.0.10-1.el7 will be installed
--> Processing Dependency: mesa-libGLES-devel(x86-64) for package: SDL2-devel-2.0.10-1.el7.x86_64
--> Finished Dependency Resolution
Error: Package: SDL2-devel-2.0.10-1.el7.x86_64 (epel)
           Requires: mesa-libGLES-devel(x86-64)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest**

**Comment by anga93** [comment]
Hello @amitgargmentor ,

these are system-specific issues and related mostly to the pulp sdk. Try to ask this in the issue section of the pulp-sdk repo.
