### ISSUE TITLE
How many cores does the pulp support at most?

### ISSUE THREAD

**Issue by First-Killer** [pulp-platform/pulp#41]
I read it is an open-source multi-core computing platform,but what's the largest number of cores?

**Comment by FrancescoConti** [comment]
The main scalability limitation of a tightly coupled cluster of cores is the timing of the L1-core interconnect. Currently, we taped out and tested PULP chips with up to 16 cores (http://asic.ethz.ch/2020/Dustin.html). Keep in mind that the main target of PULP is low-power extreme edge computing, so the benefit of going much beyond that in symmetric multi-processing is probably overrun by the limitations.
That said, people in our group are working on larger scale applications (e.g., @suehtamacv https://arxiv.org/pdf/2012.02973.pdf ) so stay tuned.

**Comment by First-Killer** [comment]
> 紧密耦合的内核集群的主要可伸缩性限制是L1内核互连的时序。目前，我们以最多16个内核（http://asic.ethz.ch/2020/Dustin.html）进行了磁带测试。请记住，PULP的主要目标是低功耗的极端边缘计算，因此，在限制上，超出对称多处理中的范围的好处可能超出了限制。
> 就是说，我们小组中的人们正在开发更大规模的应用程序（例如@suehtamacv https://arxiv.org/pdf/2012.02973.pdf），敬请关注。

Thank you!
