### ISSUE TITLE
openocd can't hart the fc core

### ISSUE THREAD

**Issue by zhangpipi-xyz** [pulp-platform/pulp#46]
Hi,
I move the pulp project from fpga xcku115-flvd1924-1-c to fpga xczu15eg-ffvb1156-2-i.the clock of the cluster is griven by the soc_clk_rst_gen module same as the clk of the fc.
However,openocd can hart the fc core on the platform of the  xcku115-flvd1924-1-c；and can't hart the fc core on the platform of the xczu15eg-ffvb1156-2-i,the error is unable to halt hart 992;Target not examined yet and so on.
On the other hand ,if the clk of the cluster is 1'b0 always;the openocd can hart the fc core on the platform  xczu15eg-ffvb1156-2-i.
The version of the openocd is Open On-Chip Debugger 0.10.0+dev-01404-g1ba1b87 ;ubuntu 16.04;
The following pic is the situation openocd can't hart fc core.
Thank you!
![image](https://user-images.githubusercontent.com/20981289/113373299-1ec04e00-939d-11eb-83cb-a9eb148530ca.png)

**Comment by x11to** [comment]
I encountered  the same problem. How did you solved it?

**Comment by zhangpipi-xyz** [comment]
您好，晨曦收到您的来信，祝您愉快~O(∩_∩)O~
