### ISSUE TITLE
Import Error on ./update-ips

### ISSUE THREAD

**Issue by AshwiniPohekar** [pulp-platform/pulp#5]
When I try to build the RTL simulation platform for the PULP system. 
On trying to run ./update-ips this error is generated and ips.mk and rtl.mk files are not created inside the sim folder. 

```
SUMMARY
IPs updated successfully!
Traceback (most recent call last):
  File "./generate-scripts", line 7, in <module>
    from ipstools_cfg import *
  File "/home/ashwini/pulp-sdk/pulp-master/ipstools_cfg.py", line 43, in <module>
    import ipstools
  File "/home/ashwini/pulp-sdk/pulp-master/ipstools/__init__.py", line 16, in <module>
    from .ipstools import *
  File "ipstools/ipstools/__init__.py", line 13, in <module>
    from .SubIPConfig import *
  File "ipstools/ipstools/SubIPConfig.py", line 14, in <module>
    from .IPApproX_common        import *
  File "ipstools/ipstools/IPApproX_common.py", line 20, in <module>
    import yaml
ImportError: No module named yaml
```

I am also attaching a screenshot of the error from the terminal. Also, I am building the sdk before building the rtl platfrom. The sdk is built sucessfully.  

![error_pulp](https://user-images.githubusercontent.com/8349323/52263497-a205c680-292f-11e9-8356-c2c8cee8cd00.png)

**Comment by FrancescoConti** [comment]
As indicated by the last line, you need to install the YAML package.

https://stackoverflow.com/questions/14261614/how-do-i-install-the-yaml-package-for-python

**Comment by AshwiniPohekar** [comment]
I forgot to mention this but ./update-ips works without any issue for pulpissimo. Should it not have complained about this package in that case as well. 

In any case I will look into the link that you have mentioned for installing the package.

**Comment by AshwiniPohekar** [comment]
I was able to get it to work after installing the package : pyyaml.

Thanks!

**Comment by BenoitDenkinger** [comment]
I also got the same issue with yaml installed, until I realized generate-scripts is using the default python (usually python 2) and I had yaml installed for python 3. So I changed the first line to #!/usr/bin/env python3

**Comment by lso425** [comment]
I have this problem, when I put the command ./update-ips


**Traceback (most recent call last):
  File "./update-ips", line 7, in <module>
    from ipstools import ipstools
ImportError: No module named **'ipstools'****

How can I solve it?

**Comment by RaphaelKlink** [comment]
I have the same problem in the pulpissimo project. I checked multiple times if this module is installed and it finds it every time.
@Iso425 what kind of OS are you using? I am using Ubuntu 20.04 LTS.

**Comment by darphee1025** [comment]
I had this problem . When I try to build the RTL simulation platform for the PULP system.
Updating ip 'L2_tcdm_hybrid_interco'...
Traceback (most recent call last):
  File "./update-ips", line 53, in <module>
    ipdb.update_ips()
  File "ipstools/ipstools/IPDatabase.py", line 604, in update_ips
ValueError: invalid literal for int() with base 10: b''


what can I do for it?
