### ISSUE TITLE
Pulp file sync option for remote url

### ISSUE THREAD

**Issue by pranavkumar74980** [pulp-platform/pulp#94]
I am unable to sync repo for manifest file (example-> https://example.com/xyz.yaml ) present over remote url.
However, I am able to upload content on pulp repo for locally present yaml manifest files. Is there any way to do to sync remotely without downloading on localhost ? I am unable to find such things in document.
Repo details

pulp file repository list
[
  {
    "pulp_href": "/pulp/api/v3/repositories/file/file/01939b23-e5e2-726c-9bc0-8f523e847cf5/",
    "prn": "prn:file.filerepository:01939b23-e5e2-726c-9bc0-8f523e847cf5",
    "pulp_created": "2024-12-06T08:44:01.380551Z",
    "pulp_last_updated": "2024-12-06T08:44:01.404199Z",
    "versions_href": "/pulp/api/v3/repositories/file/file/01939b23-e5e2-726c-9bc0-8f523e847cf5/versions/",
    "pulp_labels": {},
    "latest_version_href": "/pulp/api/v3/repositories/file/file/01939b23-e5e2-726c-9bc0-8f523e847cf5/versions/0/",
    "name": "mpi-operator-repo",
    "description": null,
    "retain_repo_versions": null,
    "remote": null,
    "autopublish": false,
    "manifest": "PULP_MANIFEST"
  }
]

Below errors:
pulp file repository sync --name mpi-operator-repo --remote mpi-operator-remote
Started background task /pulp/api/v3/tasks/01939b24-4000-730d-825e-60b9fdc335cd/
Error: Task /pulp/api/v3/tasks/01939b24-4000-730d-825e-60b9fdc335cd/ failed: 'Error: Parsing of the manifest file failed on line:9.
Please make sure the remote URL is pointing to a valid manifest file.
The manifest file should be composed of lines in the following format: <relative_path>,<digest>,<size>.'

**Comment by FrancescoConti** [comment]
The error seems to have absolutely nothing to do with our repository. You are probably looking at the wrong repo.
